const $ = s => document.querySelector(s);
let catalogData, activeJob, selectedResult = 'overview', selectedRun = 0, pollingId = null;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (v,d=2) => v == null ? '—' : Number(v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const usd = v => v == null ? '—' : (v < 0 ? '−$' : '$') + num(Math.abs(v));
function notice(message){$('#notice').hidden=!message; $('#notice').textContent=message||'';}
async function api(path,body){const response=await fetch(path,{...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function showView(id){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===id));if(id==='history')loadHistory();}
document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>showView(e.dataset.view)));
function readConfig(){const f=new FormData($('#config-form')), config={};for(const [key,val] of f){const element=$(`[name="${key}"]`);config[key]=(element.type==='number'||['capital','margin_pct','allocation_pct'].includes(key))?Number(val):val;}config.entry_time=LabTime.inputToUtc(config.entry_time);config.exit_time=LabTime.inputToUtc(config.exit_time);const expiry=LabTime.shift(config.expiry_hour,-330);if(!expiry.endsWith(':00'))throw Error('Expiry must be on an IST half hour, such as 17:30.');config.expiry_hour=Number(expiry.slice(0,2));config.sizing_mode='btc';if(config.objective==='calmar')config.objective='sharpe';if(config.strategy_family==='options'&&config.structure==='custom')config.legs=JSON.parse(config.legs);else delete config.legs;return config;}
function applyConfig(config){if(!config||typeof config!=='object'||Array.isArray(config))throw Error('Choose a saved configuration JSON object.');const names=new Set(Array.from($('#config-form').elements).map(e=>e.name));for(const k of Object.keys(config))if(!names.has(k))throw Error('Unknown configuration field: '+k);if(config.legs!==undefined&&(!Array.isArray(config.legs)||config.legs.length>6))throw Error('Custom legs must be an array of up to six rows.');for(const [k,v] of Object.entries(config)){const el=$(`[name="${k}"]`);if(el)el.value=['entry_time','exit_time'].includes(k)?LabTime.shift(v,330):k==='expiry_hour'?LabTime.shift(String(v).padStart(2,'0')+':00',330):typeof v==='object'?JSON.stringify(v):(k==='objective'&&v==='calmar'?'sharpe':v);}renderLegs();updateStructure();updateSimpleMode();saveDraft();}
function sessionCounts(start,end,days){let eligible=0,total=0;for(let t=Date.parse(start+'T00:00:00Z'),last=Date.parse(end+'T00:00:00Z');Number.isFinite(t)&&t<=last&&total<1096;t+=86400000){total++;const weekend=[0,6].includes(new Date(t).getUTCDay());if(days==='all'||(days==='weekends')===weekend)eligible++;}return {eligible,total};}
const fieldNames={selection:'Selection method',call_delta:'Call delta',put_delta:'Put delta',delta_tolerance:'Delta tolerance',otm_pct:'OTM distance',otm_tolerance_pct:'OTM tolerance',wing_width:'Wing width',participation_pct:'Volume participation',exit_price_max_age_sec:'Exit price max age',grid_delta:'Symmetric deltas',grid_stop:'Stop loss grid',grid_tp:'Profit target grid',objective:'Experiment objective',train_pct:'Development sample',min_trades:'Minimum development trades'};
function markApplicability(name,applicable,reason){const input=$(`[name="${name}"]`),label=input?.closest('label');if(!label)return;label.classList.toggle('not-applicable',!applicable);label.querySelector('.applicability-note')?.remove();input.removeAttribute('aria-describedby');input.removeAttribute('title');if(applicable)return;const note=document.createElement('span');note.className='applicability-note';note.id='applicability-'+name;note.textContent='NOT USED · '+reason;label.append(note);input.setAttribute('aria-describedby',note.id);input.title=reason;}
function markSettingStatus(name,message){const input=$(`[name="${name}"]`),label=input?.closest('label');if(!label)return;label.querySelector('.setting-status')?.remove();if(!message)return;const note=document.createElement('span');note.className='setting-status';note.textContent='OFF · '+message;label.append(note);}
function updateApplicability(){
 const family=$('[name="strategy_family"]').value,structure=$('#structure').value,selection=$('[name="selection"]').value,mode=$('[name="mode"]').value;
 if(family==='trend'){
  for(const name of optionOnlyFields)markApplicability(name,false,'BTCUSD futures trend strategies do not use this options control.');
  const model=$('[name="trend_strategy"]').value,ma=model==='ma_crossover';
  const trendStates={trend_strategy:[true,''],trend_timeframe:[true,''],trend_direction:[true,''],trend_ma_type:[ma,'Used only by moving-average crossover.'],trend_fast:[ma,'Used only by moving-average crossover.'],trend_slow:[ma,'Used only by moving-average crossover.'],supertrend_period:[!ma,'Used only by Supertrend.'],supertrend_multiplier:[!ma,'Used only by Supertrend.'],trend_take_profit_pct:[true,''],trend_stop_loss_pct:[true,'']};
  for(const [name,[applicable,reason]] of Object.entries(trendStates))markApplicability(name,applicable,reason);
  markSettingStatus('trend_take_profit_pct',Number($('[name="trend_take_profit_pct"]').value)===0?'The futures price target is disabled.':'');
  markSettingStatus('trend_stop_loss_pct',Number($('[name="trend_stop_loss_pct"]').value)===0?'The futures price stop is disabled.':'');
  for(const name of ['min_credit','max_loss_usd','delta_exit','min_move_pct','max_move_pct'])markSettingStatus(name,'');
  const inactive=ma?'Supertrend period and multiplier':'Average type, fast average, and slow average';
  $('#applicability-summary').classList.remove('configuration-warning');
  $('#applicability-summary').innerHTML=`<b>BTCUSD futures trend following</b> · ${esc($('[name="trend_timeframe"]').value)} IST-aligned bars.<br>Signals use completed bars and trade at the next bar open. ${esc(inactive)} are not used by ${ma?'moving-average crossover':'Supertrend'}. Option strikes, DTE, Greeks, option exits, and option execution settings do not affect this run.`;
  return;
 }
 for(const name of trendOnlyFields)markApplicability(name,false,'Used only by BTCUSD futures trend strategies.');
 markSettingStatus('trend_take_profit_pct','');markSettingStatus('trend_stop_loss_pct','');
 const structureName=$('#structure option:checked').textContent,hasCall=['strangle','condor','call_spread','short_call'].includes(structure),hasPut=['strangle','condor','put_spread','short_put'].includes(structure),standardSelection=!['straddle','custom'].includes(structure),deltaSelection=standardSelection&&selection==='delta',sweep=mode==='sweep',sweepSupported=deltaSelection;
 const states={
  selection:[standardSelection,structure==='straddle'?'Short straddles use a common near-ATM strike.':'Custom legs use each leg\'s absolute delta.'],
  call_delta:[deltaSelection&&hasCall,structure==='custom'?'Use the delta inside each custom leg.':structure==='straddle'?'The common near-ATM strike determines both legs.':selection==='otm'?'OTM distance selects the strike.':`${structureName} has no short call leg.`],
  put_delta:[deltaSelection&&hasPut,structure==='custom'?'Use the delta inside each custom leg.':structure==='straddle'?'The common near-ATM strike determines both legs.':selection==='otm'?'OTM distance selects the strike.':`${structureName} has no short put leg.`],
  delta_tolerance:[structure==='custom'||deltaSelection,structure==='straddle'?'The common near-ATM strike is used without a delta target.':'OTM distance selects the strike.'],
  otm_pct:[standardSelection&&selection==='otm',structure==='straddle'?'The strategy uses a common near-ATM strike.':structure==='custom'?'Custom legs use absolute delta.':'Absolute delta selects the strike.'],
  otm_tolerance_pct:[standardSelection&&selection==='otm',structure==='straddle'?'The strategy uses a common near-ATM strike.':structure==='custom'?'Custom legs use absolute delta.':'Used only with OTM-distance selection.'],
  wing_width:[['condor','call_spread','put_spread'].includes(structure),`${structureName} has no protective long wing.`],
  participation_pct:[$('[name="execution_mode"]').value==='volume','The full-size price proxy ignores source-print volume.'],
  exit_price_max_age_sec:[$('[name="execution_mode"]').value==='price','Strict volume replay requires an eligible future print and never uses a stale-price fallback.'],
  grid_delta:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only by a delta parameter experiment.'],
  grid_stop:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only in Parameter grid mode.'],grid_tp:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only in Parameter grid mode.'],objective:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only in Parameter grid mode.'],train_pct:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only in Parameter grid mode.'],min_trades:[sweep&&sweepSupported,sweep&&!sweepSupported?'Parameter grids require a delta-selected standard structure.':'Used only in Parameter grid mode.']
 };
 for(const [name,[applicable,reason]] of Object.entries(states))markApplicability(name,applicable,reason);
 markSettingStatus('min_credit',Number($('[name="min_credit"]').value)===0?'No additional minimum-credit threshold.':'');
 markSettingStatus('max_loss_usd',Number($('[name="max_loss_usd"]').value)===0?'The dollar-loss exit is disabled.':'');
 markSettingStatus('delta_exit',Number($('[name="delta_exit"]').value)===0?'The portfolio-delta exit is disabled.':'');
 const trendOff=Number($('[name="min_move_pct"]').value)===-100&&Number($('[name="max_move_pct"]').value)===100;
 markSettingStatus('min_move_pct',trendOff?'The trailing one-hour move filter is disabled.':'');markSettingStatus('max_move_pct',trendOff?'The trailing one-hour move filter is disabled.':'');
 const unused=Object.entries(states).filter(([,state])=>!state[0]).map(([name])=>fieldNames[name]);
 const selectionName=structure==='straddle'?'common near-ATM strike':structure==='custom'?'per-leg absolute delta':selection==='delta'?'absolute-delta':'OTM-distance';
 const incompatibility=sweep&&!sweepSupported?'Parameter grid mode cannot run this combination. Choose Single configuration, or use Absolute delta with a standard non-straddle structure.<br>':'';
 $('#applicability-summary').classList.toggle('configuration-warning',Boolean(incompatibility));
 $('#applicability-summary').innerHTML=`<b>${esc(structureName)}</b> · ${esc(selectionName)} selection.<br>${incompatibility}${unused.length?`Currently unused: ${esc(unused.join(', '))}. Dimmed inputs retain their values for other strategy types but do not affect this run.`:'All visible strategy controls affect this run.'}`;
}
function updateStructure(){const structure=$('#structure').value,family=$('[name="strategy_family"]').value;if(family==='trend')$('[name="mode"]').value='single';$('#option-controls').hidden=family!=='options';$('#trend-controls').hidden=family!=='trend';$('#custom-legs').hidden=family!=='options'||structure!=='custom';$('#put-badge').textContent='−'+num($('[name="put_delta"]').value)+' Δ';$('#call-badge').textContent='+'+num($('[name="call_delta"]').value)+' Δ';$('.leg-diagram').hidden=family!=='options'||structure!=='strangle';$('#session-note').textContent=family==='trend'?'Dates define the inclusive IST futures sample. Trend positions may cross dates and close by signal, stop, target, or the final bar.':'Intraday positions only. DTE is calendar days to expiry; all legs exit in this IST session. Same-date sessions from 05:30 IST onward are supported.';}
$('#config-form').addEventListener('input',()=>{updateStructure();updateSimpleMode();saveDraft();});
let advancedSettings = false;
const essentialFields = new Set(['strategy_family','name','structure','selection','otm_pct','otm_tolerance_pct','quantity_btc','start','end','entry_time','exit_time','days','call_delta','put_delta','wing_width','take_profit_pct','stop_loss_pct','trend_strategy','trend_timeframe','trend_direction','trend_ma_type','trend_fast','trend_slow','supertrend_period','supertrend_multiplier','trend_take_profit_pct','trend_stop_loss_pct']);
const optionOnlyFields=new Set(['structure','selection','dte','call_delta','put_delta','delta_tolerance','otm_pct','otm_tolerance_pct','wing_width','entry_time','exit_time','entry_window_min','entry_check_interval_min','days','take_profit_pct','stop_loss_pct','risk_trigger_basis','min_credit','max_loss_usd','delta_exit','min_iv','max_iv','min_move_pct','max_move_pct','execution_mode','participation_pct','latency_sec','fill_timeout_sec','max_age_sec','exit_price_max_age_sec','spot_age_sec','fee_cap_pct','rate_pct','expiry_hour','mode','grid_delta','grid_stop','grid_tp','objective','train_pct','min_trades']);
const trendOnlyFields=new Set(['trend_strategy','trend_timeframe','trend_direction','trend_ma_type','trend_fast','trend_slow','supertrend_period','supertrend_multiplier','trend_take_profit_pct','trend_stop_loss_pct']);
function updateSimpleMode(){
  const structure=$('#structure').value,family=$('[name="strategy_family"]').value;
  updateStructure();
  updateApplicability();
  for(const el of $('#config-form').elements){
    if(!el.name||el.name==='legs')continue;
    const label=el.closest('label');if(!label)continue;
    let visible=advancedSettings||essentialFields.has(el.name);
    if(family==='trend'&&optionOnlyFields.has(el.name))visible=advancedSettings;
    if(family==='options'&&trendOnlyFields.has(el.name))visible=false;
    if(!advancedSettings&&family==='options'){
      if(el.name==='selection')visible=!['straddle','custom'].includes(structure);
      if(el.name==='otm_pct')visible=$('[name="selection"]').value==='otm'&&!['straddle','custom'].includes(structure);
      if(el.name==='otm_tolerance_pct')visible=$('[name="selection"]').value==='otm'&&!['straddle','custom'].includes(structure);
      if(el.name==='call_delta')visible=$('[name="selection"]').value==='delta'&&['strangle','condor','call_spread','short_call'].includes(structure);
      if(el.name==='put_delta')visible=$('[name="selection"]').value==='delta'&&['strangle','condor','put_spread','short_put'].includes(structure);
      if(el.name==='wing_width')visible=['condor','call_spread','put_spread'].includes(structure);
    }
    if(el.name==='participation_pct'&&$('[name="execution_mode"]').value==='price')visible=false;
    if(['capital','allocation_pct','margin_pct'].includes(el.name))visible=false;
    label.hidden=!visible;
  }
  for(const detail of $('#config-form').querySelectorAll('details')){
    const experiment=family==='options'&&detail.id==='sweep-panel'&&$('[name="mode"]').value==='sweep';
    detail.hidden=!advancedSettings&&!experiment&&!Array.from(detail.querySelectorAll('label')).some(l=>!l.hidden);
    if(experiment){detail.hidden=false;detail.querySelectorAll('label').forEach(l=>l.hidden=false);}
  }
  const qty=Number($('[name="quantity_btc"]').value);
  const start=$('[name="start"]').value,end=$('[name="end"]').value,days=$('[name="days"]').value;
  const {eligible:count,total}=sessionCounts(start,end,days);
  const legs=family==='options'&&structure==='custom'?JSON.parse($('[name="legs"]').value):null;
  const shortCount=family==='trend'?1:legs?legs.filter(l=>l.side==='sell').reduce((n,l)=>n+l.ratio,0):['strangle','straddle','condor'].includes(structure)?2:1;
  const execution=$('[name="execution_mode"]').value;
  const fillText=execution==='price'
    ?`Full-size price proxy: the requested BTC quantity fills at an observed option trade price, adjusted for slippage. Exit fallback is limited to a ${esc($('[name="exit_price_max_age_sec"]').value)}-second-old observed trade and is flagged in the ledger.`
    :`Strict liquidity replay: each fill is limited to ${esc($('[name="participation_pct"]').value)}% of observed print volume. Large BTC sizes can remain unresolved and halt later dates.`;
  $('#run-preview').innerHTML=family==='trend'?`<b>${esc(num(qty,3))} BTC futures position</b> · ${esc($('[name="trend_timeframe"]').value)} IST-aligned bars · ${esc($('[name="trend_direction"] option:checked').textContent)}.<br>${total} calendar days · ${esc(start)} → ${esc(end)}.<br>Signals use completed bars and execute at the next bar open with ${esc($('[name="slippage_pct"]').value)}% adverse slippage.`:`<b>${esc(num(qty,3))} BTC per ${legs?'base ':''}leg</b> · ${esc(num(qty*shortCount,3))} BTC total short quantity.<br>${count} eligible sessions across ${total} calendar days · ${esc(start)} → ${esc(end)}.<br>${fillText}`;

}
$('#advanced-toggle').onclick=()=>{advancedSettings=!advancedSettings;$('#advanced-toggle').textContent=advancedSettings?'Hide advanced settings':'Show advanced settings';$('#advanced-toggle').setAttribute('aria-pressed',String(advancedSettings));updateSimpleMode();};
function renderRunExplanation(run){
  const c=run.config,m=run.metrics,skips=run.skips;
  const summary=$('#run-explanation');summary.hidden=false;
  const filled=run.trades.filter(t=>t.entry_complete).length;
  const trend=c.strategy_family==='trend',execution=trend?`${c.trend_strategy==='ma_crossover'?`${c.trend_fast}/${c.trend_slow} ${c.trend_ma_type.toUpperCase()} crossover`:`Supertrend ${c.supertrend_period} × ${c.supertrend_multiplier}`} · ${c.trend_timeframe} IST bars · next-bar execution`:c.execution_mode==='price'?'Full-size observed-price proxy':'Strict observed-volume replay';
  const sample=trend?`${esc(c.start)} → ${esc(c.end)} · requested ${num(c.quantity_btc,3)} BTC futures position · ${esc(execution)}.`:`${esc(c.start)} → ${esc(c.end)} · ${esc(c.days)} · requested ${num(c.quantity_btc,3)} BTC per base leg · ${execution}.`;
  summary.innerHTML=`<b>What this run actually tested</b><br>${sample}<br>${m.trade_count} closed positions, ${filled} complete entries, ${m.unresolved_count} unresolved.<br>${trend?`${run.quality.bars||0} constructed bars from ${(run.quality.source_ticks||0).toLocaleString()} futures ticks`:`${skips.weekday_filter||0} dates excluded by the day filter · ${skips.no_entry_days||0} dates without an entry`} · ${run.missing_days.length} dates missing data.<br>${skips.minimum_credit?`${skips.minimum_credit} entry attempts failed the ${usd(c.min_credit)} minimum total premium requirement. `:''}${m.trade_count<20?'This sample is too small to judge the strategy; headline Sharpe is hidden. ':''}<br>${m.net_pnl==null?'Some exposure remains unresolved; total P&L is unavailable.':`Closed-position P&L after slippage, before fees: ${usd(run.trades.filter(t=>t.net_pnl!=null).reduce((n,t)=>n+t.gross_pnl,0))}; closed-position fees: ${usd(run.trades.filter(t=>t.net_pnl!=null).reduce((n,t)=>n+t.fees,0))}; net: ${usd(m.net_pnl)}.`}<br>${activeJob.elapsed_seconds!=null?`Completed in ${num(activeJob.elapsed_seconds,1)} seconds. `:''}Replay processes historical ticks without waiting for market time; indexed data is reused when source files are unchanged.`;
}
let strategyIdeas = [], ideaFilter = 'All', showAllIdeas = false;
function renderIdeas(){
  const matches = strategyIdeas.filter(i=>ideaFilter==='All'||i.category===ideaFilter);
  const visible = showAllIdeas ? matches : matches.slice(0,3);
  $('#idea-cards').innerHTML=visible.map(i=>`<article class="idea-card"><span class="tag">${esc(i.category)}</span><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><ul>${i.rules.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><small>${esc(i.caution)}</small><button type="button" class="secondary" data-load-idea="${esc(i.id)}">Load strategy ↗</button></article>`).join('');
  $('#more-ideas').hidden=matches.length<=3;
  $('#more-ideas').textContent=showAllIdeas?'Show fewer ideas ↑':`Show all ${matches.length} ideas ↓`;
  document.querySelectorAll('[data-load-idea]').forEach(b=>b.onclick=()=>{
    try{
      const idea=strategyIdeas.find(i=>i.id===b.dataset.loadIdea);
      const quantity=Number($('[name="quantity_btc"]').value);
      applyConfig(idea.preserve_quantity===false?{...idea.config,sizing_mode:'btc'}:{...idea.config,quantity_btc:quantity,sizing_mode:'btc'});
      $('#sweep-panel').open=idea.config.mode==='sweep';
      $('#idea-status').hidden=false;
      $('#idea-status').textContent=`Loaded: ${idea.title}. Rules loaded; your BTC size was kept. Review the dates and rules, then click Run backtest. Existing results still belong to their original run.`;
      notice($('#idea-status').textContent);
      $('.builder').scrollTop=0;
      $('.builder').scrollIntoView({block:'start',behavior:'smooth'});
      $('[name="name"]').focus({preventScroll:true});
    }catch(e){notice(e.message);}
  });
}
async function loadIdeas(){try{strategyIdeas=await api('/api/presets');renderIdeas();}catch(e){$('#idea-cards').textContent='Could not load ideas. Refresh the page to retry. '+e.message;}}
document.querySelectorAll('[data-idea-filter]').forEach(b=>b.onclick=()=>{
  ideaFilter=b.dataset.ideaFilter;showAllIdeas=false;
  document.querySelectorAll('[data-idea-filter]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});
  renderIdeas();
});
$('#more-ideas').onclick=()=>{showAllIdeas=!showAllIdeas;renderIdeas();};
$('#toggle-ideas').onclick=()=>{const body=$('#idea-body');body.hidden=!body.hidden;$('#toggle-ideas').textContent=body.hidden?'Browse ideas':'Hide ideas';$('#toggle-ideas').setAttribute('aria-expanded',String(!body.hidden));};
async function loadExample(){const config=await api('/api/presets/one-btc-example');applyConfig(config);showView('workspace');notice('1 BTC example loaded: June 1 20-delta short strangle, Every day, using the full-size observed-price proxy. Click Run backtest.');}
$('#load-example').onclick=()=>loadExample().catch(e=>notice(e.message));
$('#save-config').onclick=()=>{try{const blob=new Blob([JSON.stringify(readConfig(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='options-lab-config.json';a.click();URL.revokeObjectURL(a.href);notice('Configuration downloaded. Import it from Run history to reuse it.');}catch(e){notice(e.message);}};
$('#import-button').onclick=()=>$('#import-file').click();
$('#import-file').onchange=async e=>{try{applyConfig(JSON.parse(await e.target.files[0].text()));showView('workspace');notice('Configuration loaded. Review the controls before running.');}catch(e){notice('Could not import: '+e.message);}};
const initialResults=$('.results').innerHTML;
let submitting=false, runClock=null, elapsedBase=0, clockStarted=0;
function feedback(message,error=false){$('#run-feedback').hidden=!message;$('#run-feedback').textContent=message;$('#run-feedback').classList.toggle('negative',error);}
function setBusy(busy){$('#cancel').disabled=busy&&!activeJob;$('#run-button').disabled=busy;$('#run-button').textContent=busy?'◌ Backtest running…':'▶ Run backtest';$('#progress-area').hidden=!busy;if(!busy){clearInterval(runClock);runClock=null;}}
function timeLabel(seconds){return seconds<60?`${Math.round(seconds)}s`:`${Math.floor(seconds/60)}m ${Math.round(seconds%60)}s`;}
function updateClock(){
 const elapsed=elapsedBase+(Date.now()-clockStarted)/1000;
 const progress=activeJob?.progress||0;
 const eta=progress>0.02&&elapsed>3?`~${timeLabel(elapsed*(1-progress)/progress)} remaining (estimate)`:'ETA estimating · indexing and liquidity vary';
 $('#progress-time').textContent=`${timeLabel(elapsed)} elapsed · ${eta}`;
}
function resetResults(){pollingId=null;activeJob=null;selectedResult='overview';selectedRun=0;localStorage.removeItem('optionsLabActive');clearInterval(runClock);runClock=null;$('.results').innerHTML=initialResults;bindResultControls();feedback('');notice('Result view cleared. Saved history is unchanged.');}
function bindResultControls(){
 $('#clear-result').onclick=()=>{if(activeJob&&['queued','running'].includes(activeJob.status)){notice('Cancel the active run before clearing its progress.');return;}resetResults();};
 $('#cancel').onclick=async()=>{try{if(activeJob){await api(`/api/runs/${activeJob.id}/cancel`,{});feedback('Cancellation requested. Waiting for the current operation to stop…');$('#progress-label').textContent='Cancellation requested…';}}catch(e){feedback('Cancel failed: '+e.message,true);}};
 document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{selectedResult=b.dataset.result;document.querySelectorAll('[data-result]').forEach(e=>e.classList.toggle('active',e===b));if(activeJob?.result)renderResultTab();});
}
bindResultControls();
$('#config-form').onsubmit=async e=>{
 e.preventDefault();if(submitting||['queued','running'].includes(activeJob?.status)){feedback('A backtest is already active. Follow progress or cancel it.');return;}
 const invalid=Array.from($('#config-form').elements).find(el=>el.willValidate&&!el.validity.valid);
 if(invalid){advancedSettings=true;$('#advanced-toggle').textContent='Hide advanced settings';$('#advanced-toggle').setAttribute('aria-pressed','true');updateSimpleMode();const detail=invalid.closest('details');if(detail)detail.open=true;invalid.closest('label').hidden=false;feedback(`Please fix ${invalid.closest('label').textContent.trim()}: ${invalid.validationMessage}`,true);invalid.focus();invalid.reportValidity();return;}
 const sessions=sessionCounts($('[name="start"]').value,$('[name="end"]').value,$('[name="days"]').value);
 if($('[name="strategy_family"]').value==='options'&&!sessions.eligible){const message=`Trade days = ${$('[name="days"] option:checked').textContent} excludes every selected date. Choose Every day or change the date range.`;feedback(message,true);notice(message);$('[name="days"]').focus();return;}
 submitting=true;activeJob=null;feedback('Starting backtest…');notice('Submitting your configuration…');setBusy(true);$('#progress-label').textContent='Starting backtest…';$('#progress-bar').style.width='0%';$('#progress-time').textContent='Connecting to local engine…';
 try{const job=await api('/api/runs',readConfig());localStorage.setItem('optionsLabActive',job.id);await poll(job.id);}
 catch(e){setBusy(false);feedback('Could not start: '+e.message+' Check the local server and try again.',true);notice('Could not start backtest: '+e.message);}
 finally{submitting=false;}
};
async function poll(id){
 pollingId=id;localStorage.setItem('optionsLabActive',id);
 try{
  const job=await api('/api/runs/'+id);if(pollingId!==id)return;activeJob=job;
  const running=['queued','running'].includes(job.status);setBusy(running);$('#run-status').textContent=job.status.toUpperCase();$('#progress-label').textContent=job.message;$('#progress-bar').style.width=Math.max(2,job.progress*100)+'%';
  if(running){elapsedBase=job.elapsed_seconds||0;clockStarted=Date.now();updateClock();if(!runClock)runClock=setInterval(updateClock,1000);feedback(job.message);setTimeout(()=>{if(pollingId===id)poll(id);},1000);}
  else{const unresolved=job.result?.runs?.some(r=>r.metrics.unresolved_count);const message=job.status==='completed'?(unresolved?`Replay stopped with unresolved exposure after ${timeLabel(job.elapsed_seconds||0)}. Review the failed fills below.`:`Backtest complete in ${timeLabel(job.elapsed_seconds||0)}. Results are ready.`):job.message;feedback(message,job.status==='failed'||unresolved);localStorage.removeItem('optionsLabActive');if(job.result){selectedRun=job.result.selected_index;renderResults();}else notice(job.message);}
 }catch(e){if(pollingId!==id)return;setBusy(false);feedback('Could not read progress: '+e.message+'. Open Run history to reconnect; the server may still be running the test.',true);notice('Progress connection failed. Check Run history to reconnect.');}
}
async function deleteRuns(id){
 try{const result=await api(id?'/api/runs/delete':'/api/runs/clear',id?{id}:{});if(result.deleted.includes(activeJob?.id))resetResults();await loadHistory();notice(`${result.deleted.length} runs removed. ${result.active_runs_kept?'Active runs were kept. ':''}Deleted files are recoverable in outputs/options_lab/deleted_runs.`);}catch(e){notice('Could not delete runs: '+e.message);}
}
$('#clear-runs').onclick=()=>deleteRuns();

async function loadHistory(){try{const runs=await api('/api/runs');$('#history-content').innerHTML=runs.length?runs.map(j=>`<div class="run-item"><div><strong>${esc(j.request.name)}</strong><small>${esc(j.request.start)} → ${esc(j.request.end)} · ${esc(LabTime.timestamp(j.created))}</small></div><span class="pill">${esc(j.status)}</span><button class="secondary" data-load="${j.id}">Open result</button><button class="text-button" data-reuse="${j.id}">Reuse rules ↗</button><button class="text-button" data-delete="${j.id}" ${['queued','running'].includes(j.status)?'disabled':''}>Delete</button></div>`).join(''):'<p class="muted">Your completed and interrupted runs will be saved here.</p>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRuns(b.dataset.delete));document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{showView('workspace');poll(b.dataset.load);});document.querySelectorAll('[data-reuse]').forEach(b=>b.onclick=async()=>{const j=await api('/api/runs/'+b.dataset.reuse);applyConfig(j.request);showView('workspace');});}catch(e){notice(e.message);}}
async function init(){loadIdeas();try{renderLegs();updateSimpleMode();const draft=localStorage.getItem('optionsLabDraft');if(draft){try{applyConfig(JSON.parse(draft));}catch(e){localStorage.removeItem('optionsLabDraft');notice('An invalid saved browser draft was ignored.');}}if(!localStorage.getItem('optionsLabBtcSizeV2')){$('[name="quantity_btc"]').value='1';localStorage.setItem('optionsLabBtcSizeV2','1');updateSimpleMode();saveDraft();}const preset=new URLSearchParams(location.search).get('preset');if(preset==='strangle-20-delta'||preset==='one-btc-example'){await loadExample();history.replaceState(null,'','/');}catalogData=await api('/api/catalog');const months=catalogData.months;$('#data-title').textContent=`${months.length} monthly option files · ${months[0]?.month||'No data'} — ${months.at(-1)?.month||''}`;$('#data-detail').textContent=catalogData.kind;$('#data-size').textContent=num(catalogData.bytes/1024**3,1)+' GB ON DISK';$('#catalog-root').textContent=catalogData.root;$('#catalog-content').innerHTML='<div class="table-wrap"><table><thead><tr><th>Month</th><th>Options</th><th>Futures</th><th>Pair status</th></tr></thead><tbody>'+months.map(m=>`<tr><td>${m.month}</td><td>${num(m.option_bytes/1024**2,1)} MB</td><td>${num(m.future_bytes/1024**2,1)} MB</td><td>${m.paired?'Both files present':'Missing futures'}</td></tr>`).join('')+'</tbody></table></div>';const id=localStorage.getItem('optionsLabActive');if(id){const previous=await api('/api/runs/'+id);if(['queued','running'].includes(previous.status))poll(id);else localStorage.removeItem('optionsLabActive');}}catch(e){notice(e.message);}}
function saveDraft(){try{localStorage.setItem('optionsLabDraft',JSON.stringify({...readConfig(),legs:JSON.parse($('[name="legs"]').value)}));}catch(e){/* Invalid unfinished input remains editable. */}}
function renderLegs(){let legs;try{legs=JSON.parse($('[name="legs"]').value);}catch(e){legs=[];}$('#leg-rows').innerHTML=legs.map((l,i)=>`<div class="leg-editor" data-leg-row="${i}"><label>Side<select data-leg-key="side"><option value="sell" ${l.side==='sell'?'selected':''}>Sell</option><option value="buy" ${l.side==='buy'?'selected':''}>Buy</option></select></label><label>Type<select data-leg-key="type"><option value="P" ${l.type==='P'?'selected':''}>Put</option><option value="C" ${l.type==='C'?'selected':''}>Call</option></select></label><label>Absolute delta<input data-leg-key="delta" type="number" min="0.01" max="0.95" step="0.01" value="${esc(l.delta)}"></label><label>Ratio<input data-leg-key="ratio" type="number" min="1" max="10" value="${esc(l.ratio)}"></label><button type="button" class="text-button" data-remove-leg="${i}" aria-label="Remove leg ${i+1}">×</button></div>`).join('');document.querySelectorAll('[data-leg-key]').forEach(el=>el.onchange=()=>{const rows=Array.from(document.querySelectorAll('[data-leg-row]')).map(row=>Object.fromEntries(Array.from(row.querySelectorAll('[data-leg-key]')).map(input=>[input.dataset.legKey,['delta','ratio'].includes(input.dataset.legKey)?Number(input.value):input.value])));$('[name="legs"]').value=JSON.stringify(rows);updateSimpleMode();saveDraft();});document.querySelectorAll('[data-remove-leg]').forEach(el=>el.onclick=()=>{legs=JSON.parse($('[name="legs"]').value);legs.splice(Number(el.dataset.removeLeg),1);$('[name="legs"]').value=JSON.stringify(legs);renderLegs();updateSimpleMode();saveDraft();});$('#add-leg').disabled=legs.length>=6;}
$('#add-leg').onclick=()=>{const legs=JSON.parse($('[name="legs"]').value);if(legs.length<6)legs.push({type:'C',side:'buy',delta:.1,ratio:1});$('[name="legs"]').value=JSON.stringify(legs);renderLegs();updateSimpleMode();saveDraft();};
init();
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function stats(items){return '<div class="stats-list">'+items.map(([label,value])=>`<div class="stat"><small>${esc(label)}</small><strong>${value}</strong></div>`).join('')+'</div>';}
function equityChart(curve){if(!curve?.length)return '<p class="muted">No marked equity observations.</p>';const W=800,H=310,left=70,right=16,top=18,bottom=37;const minT=Date.parse(curve[0].time),maxT=Date.parse(curve.at(-1).time);let lo=Math.min(...curve.map(p=>p.equity)),hi=Math.max(...curve.map(p=>p.equity));const padding=Math.max((hi-lo)*.15,1);lo-=padding;hi+=padding;const x=t=>left+(Date.parse(t)-minT)/(maxT-minT||1)*(W-left-right);const y=v=>top+(hi-v)/(hi-lo)*(H-top-bottom-45);const pts=curve.map(p=>`${x(p.time).toFixed(1)},${y(p.equity).toFixed(1)}`).join(' ');const ddmax=Math.max(...curve.map(p=>-p.drawdown),1);const dd=curve.map(p=>`${x(p.time).toFixed(1)},${(H-bottom-35-p.drawdown/ddmax*30).toFixed(1)}`).join(' ');let grid='';for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;grid+=`<line x1="${left}" y1="${y(v)}" x2="${W-right}" y2="${y(v)}" stroke="#30383c" stroke-dasharray="3 5"/><text x="${left-10}" y="${y(v)+4}" text-anchor="end" class="chart-label">${num(v,0)}</text>`;}return `<svg class="chart-real" viewBox="0 0 ${W} ${H}" role="img" aria-label="Cumulative P&L in USD and observed drawdown"><defs><linearGradient id="equityFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#c2ff74" stop-opacity=".16"/><stop offset="1" stop-color="#c2ff74" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${left},${H-bottom-45} ${pts} ${W-right},${H-bottom-45}" fill="url(#equityFill)"/><polyline points="${pts}" fill="none" stroke="#c2ff74" stroke-width="1.8"/><polyline points="${dd}" fill="none" stroke="#ed8c92" stroke-width="1.3"/><text x="${left}" y="${H-8}" class="chart-label">${LabTime.timestamp(curve[0].time).slice(0,16)+' IST'}</text><text x="${W-right}" y="${H-8}" text-anchor="end" class="chart-label">${LabTime.timestamp(curve.at(-1).time).slice(0,16)+' IST'}</text></svg>`;}
function renderResults(){const result=activeJob.result,run=result.runs[selectedRun],m=run.metrics,trend=run.config.strategy_family==='trend';$('#result-title').textContent=run.config.name;$('#run-status').textContent=m.unresolved_count?'UNRESOLVED EXPOSURE':'COMPLETED';$('#progress-area').hidden=true;document.querySelector('[data-result="risk"]').textContent=trend?'Risk':'Risk & Greeks';renderRunExplanation(run);$('#metrics').innerHTML=[['Net P&L',usd(m.net_pnl),'After fees & slippage',m.net_pnl>=0?'positive':'negative'],['Max drawdown',usd(m.max_drawdown),run.config.sizing_mode==='btc'?'Observed USD loss from peak':'Observed · '+num(m.max_drawdown_pct)+'%','negative'],['Sharpe ratio',m.trade_count<20?'Too few trades':num(m.sharpe),m.trade_count<20?`${m.trade_count} closed · need 20 to display`:run.config.sizing_mode==='btc'?'Daily P&L · √365':'Daily returns · √365',''],['Win rate',m.win_rate==null?'—':num(m.win_rate,1)+'%',m.trade_count+' closed positions','']].map(([l,v,s,c])=>`<article><small>${l}</small><strong class="${c}">${v}</strong><span>${s}</span></article>`).join('');$('#equity-chart').className='';$('#equity-chart').innerHTML=m.unresolved_count?'<div class="empty-card"><h3>P&L chart unavailable</h3><p>An option position could not be closed. A completed curve would hide that open exposure; inspect Trade ledger.</p></div>':equityChart(run.config.sizing_mode==='btc'?m.curve:m.curve.map(p=>({...p,equity:p.equity-run.config.capital})));$('#exports').hidden=false;$('#export-json').href=`/api/runs/${activeJob.id}/export`;$('#export-csv').href=`/api/runs/${activeJob.id}/trades.csv?variant=${selectedRun}`;const warnings=[];if(m.unresolved_count)warnings.push('An exit could not be completed. Further entries stopped; headline performance is unavailable. Inspect Audit and the trade ledger.');if(run.missing_days.length)warnings.push(`${run.missing_days.length} dates have missing source data. This is a partial sample.`);if(m.trade_count<20)warnings.push('Small sample: fewer than 20 closed positions. Ratios are descriptive, not evidence of a stable edge.');if(result.runs.length>1&&!result.winner_selected)warnings.push('No configuration met the development ranking requirements. The first variant is shown; no winner was selected.');if(m.mark_coverage_pct!=null&&m.mark_coverage_pct<95)warnings.push(`${num(m.mark_coverage_pct,1)}% of risk events had fresh marks. Drawdown may be understated.`);notice(warnings.join(' '));renderResultTab();}
document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{selectedResult=b.dataset.result;document.querySelectorAll('[data-result]').forEach(e=>e.classList.toggle('active',e===b));if(activeJob?.result)renderResultTab();});
function renderResultTab(){const result=activeJob.result,run=result.runs[selectedRun],m=run.metrics,c=run.config,out=$('#result-content');
if(selectedResult==='overview'){const monthly={};for(const t of run.trades.filter(t=>t.net_pnl!=null)){const month=t.date.slice(0,7);monthly[month]=(monthly[month]||0)+t.net_pnl;}const trend=c.strategy_family==='trend',descriptor=trend?`${c.trend_strategy.replaceAll('_',' ')} · ${c.trend_timeframe} bars · ${num(c.quantity_btc,3)} BTC`:`${c.structure.replaceAll('_',' ')} · ${num(c.quantity_btc,3)} BTC per base leg · ${LabTime.shift(c.entry_time,330)}–${LabTime.shift(c.exit_time,330)} IST`;out.innerHTML=stats([[trend?'Futures position':'Position size',num(c.quantity_btc,3)+(trend?' BTC':' BTC / leg')],['Profit factor',num(m.profit_factor)],['Sortino',m.trade_count<20?'Too few trades':num(m.sortino)],['Average trade',usd(m.average_trade)],['Total fees',usd(m.fees)],['Slippage cost',usd(m.slippage)],['Best trade',usd(m.best_trade)],['Worst trade',usd(m.worst_trade)],['Calendar sample',m.sample_days+' days']])+`<div class="info-banner">${esc(descriptor)} · ${c.start} → ${c.end}<br>${trend?'Signals use completed bars and next-bar execution. Intrabar stop/target collisions choose the stop.':'Observed drawdown uses available tick marks; execution windows and stale intervals can hide additional losses.'}</div><h3 style="font-size:14px">Monthly realized P&L</h3><div class="heatmap">${Object.entries(monthly).map(([month,p])=>`<div class="heat-cell ${p<0?'loss':''}"><small>${month}</small><b class="${p<0?'negative':'positive'}">${usd(p)}</b></div>`).join('')}</div>`;}
if(selectedResult==='trades'){
 const trend=c.strategy_family==='trend';
 const headers=trend?['Exit date / details','Direction','Entry IST','Exit IST','Exit reason','Fees','Net P&L']:['Date / details','Entry IST','Exit','Credit','Fees','Net P&L','Status'];
 const rows=run.trades.map((t,i)=>trend
  ?[`<button data-trade="${i}">${esc(t.date)} ↗</button>`,esc(t.direction),esc(LabTime.timestamp(t.entry_time)),esc(LabTime.timestamp(t.exit_time)),esc(t.exit_reason.replaceAll('_',' ')),usd(t.fees),`<span class="${t.net_pnl<0?'negative':'positive'}">${usd(t.net_pnl)}</span>`]
  :[`<button data-trade="${i}">${esc(t.date)} ↗</button>`,esc(LabTime.timestamp(t.entry_time)),esc(t.exit_reason.replaceAll('_',' ')),usd(t.entry_credit),usd(t.fees),`<span class="${t.net_pnl<0?'negative':'positive'}">${usd(t.net_pnl)}</span>`,esc(t.status)]);
 out.innerHTML=`<div class="subhead"><h3>Position ledger</h3><small>${trend?'BTCUSD futures entries and exits':'Click a date for legs, Greeks & individual fills'}</small></div>`+table(headers,rows)+'<div id="trade-detail"></div>';
 document.querySelectorAll('[data-trade]').forEach(b=>b.onclick=()=>{
  const t=run.trades[Number(b.dataset.trade)];
  $('#trade-detail').innerHTML=trend
   ?`<div class="info-banner">Signal completed ${esc(LabTime.timestamp(t.decision_time))}<br>Entry ${esc(LabTime.timestamp(t.entry_time))} at ${usd(t.underlying_entry)}<br>Exit ${esc(LabTime.timestamp(t.exit_time))} at ${usd(t.underlying_exit)}<br>${esc(t.execution_window_risk)}</div>`+stats([['Quantity',num(t.quantity_btc,3)+' BTC'],['MAE',usd(t.mae)],['MFE',usd(t.mfe)],['Slippage',usd(t.slippage)],['Fees',usd(t.fees)],['Net P&L',usd(t.net_pnl)]])
   :'<div class="info-banner">Decision '+esc(LabTime.timestamp(t.decision_time))+'<br>Entry complete '+esc(LabTime.timestamp(t.entry_time))+'<br>Exit trigger '+esc(LabTime.timestamp(t.exit_trigger))+'<br>'+esc(t.execution_window_risk)+'</div>'+table(['Leg','Side','BTC filled','IV','Delta','Gamma','Theta/day','Vega/1pt'],t.legs.map(l=>[esc(l.symbol),esc(l.side),num(l.quantity_btc,3),num(l.greeks.iv*100,1)+'%',num(l.greeks.delta,3),num(l.greeks.gamma,6),num(l.greeks.theta),num(l.greeks.vega)]))+`<details><summary>Individual fill evidence & risk path</summary><pre class="ledger-detail">${esc(JSON.stringify(LabTime.evidence(t),null,2))}</pre></details>`;
 });
}
if(selectedResult==='risk'){const entries=run.trades,trend=c.strategy_family==='trend';out.innerHTML=stats([['Observed worst excursion',usd(entries.length?Math.min(...entries.map(t=>t.mae)):null)],['Trade expected shortfall (95%)',usd(m.expected_shortfall_95)],['Mark coverage',num(m.mark_coverage_pct,1)+'%'],[trend?'Largest notional':'Peak reserve',usd(entries.length?Math.max(...entries.map(t=>t.margin_reserve)):null)],[trend?'Constructed bars':'Incomplete entries',trend?run.quality.bars:run.quality.incomplete_entries],['Unresolved positions',m.unresolved_count]])+(trend?'<div class="info-banner">Futures risk uses bar high/low excursions. The engine knows each bar’s extremes but not which extreme occurred first.</div>'+table(['Exit date','Direction','Entry','Exit','MAE','MFE'],entries.map(t=>[esc(t.date),esc(t.direction),usd(t.underlying_entry),usd(t.underlying_exit),usd(t.mae),usd(t.mfe)])):'<div class="info-banner">Greeks below are model estimates at the entry decision, signed and scaled by filled BTC. Vega is USD per 1 volatility point; theta is USD per day.</div>'+table(['Date','Portfolio Δ (BTC)','Gamma','Theta / day','Vega / 1pt','MAE','MFE'],entries.map(t=>[esc(t.date),num(t.entry_greeks.delta,4),num(t.entry_greeks.gamma,6),usd(t.entry_greeks.theta),usd(t.entry_greeks.vega),usd(t.mae),usd(t.mfe)])));}
if(selectedResult==='compare'){if(result.runs.length===1){out.innerHTML=c.strategy_family==='trend'?'<div class="empty-card"><h3>Load another trend template.</h3><p>Trend parameter grids are not available yet. Change the timeframe or indicator settings, run again, and compare the saved results in Run history.</p></div>':'<div class="empty-card"><h3>Test the neighborhood of your idea.</h3><p>Open Parameter experiment in the builder and choose a grid of deltas, stops, and profit targets. Use at least 10 days; larger samples are more informative.</p></div>';return;}out.innerHTML=`<div class="subhead"><h3>Development → holdout</h3><span class="tag">SPLIT ${result.split_date}</span></div><p class="muted" style="font-size:12px;margin-bottom:16px">Ranking uses development ${esc(c.objective)} only. Holdout starts ${result.split_date}. ${result.winner_selected?'Selected configuration is marked below.':'No eligible winner.'} Repeatedly tuning to the holdout invalidates it.</p>`+table(['Variant','|Δ|','SL %','TP %','Dev trades','Dev P&L','Dev Sharpe','Dev DD','Holdout P&L','Holdout Sharpe','Status'],result.runs.map((r,i)=>[`<button data-variant="${i}">${result.winner_selected&&i===result.selected_index?'★ ':''}#${i+1} ↗</button>`,num(r.config.call_delta),num(r.config.stop_loss_pct,0),num(r.config.take_profit_pct,0),r.development.trade_count,usd(r.development.net_pnl),num(r.development.sharpe),usd(r.development.max_drawdown),usd(r.holdout.net_pnl),num(r.holdout.sharpe),r.eligible?'Eligible':'Insufficient / invalid']));document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{selectedRun=Number(b.dataset.variant);renderResults();});}
if(selectedResult==='audit'){const trend=c.strategy_family==='trend';out.innerHTML=`<div class="subhead"><h3>Evidence & limitations</h3><span class="tag">${esc(result.engine_version)}</span></div><div class="info-banner">${result.assumptions.map(esc).join('<br>')}</div>`+stats([['Missing source dates',run.missing_days.length],[trend?'Constructed bars':'Invalid Greek observations',trend?run.quality.bars:run.quality.invalid_greek_events],['Closed realized P&L',usd(m.realized_closed_pnl)]])+'<h3 style="font-size:14px;margin:24px 0 10px">Entry attempts & skipped dates</h3>'+table(['Reason','Count'],Object.entries(run.skips).map(([k,v])=>[esc(k.replaceAll('_',' ')),v]))+'<small>Selection reasons count minute-by-minute attempts; no-entry and missing-data counters count days.</small>'+`<details><summary>Source fingerprints & ingestion quality</summary><pre class="ledger-detail">${esc(JSON.stringify(result.sources.map(s=>({path:s.path,bytes:s.bytes,sha256:s.sha256,quality:s.quality,days:s.days.length})),null,2))}</pre></details><details><summary>Exact configuration (UTC storage; controls display IST)</summary><pre class="ledger-detail">${esc(JSON.stringify(c,null,2))}</pre></details>`;}}
// The visible configuration is also exposed to supporting agent-enabled browsers.
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_options_configuration',description:'Read the visible Bitcoin options strategy controls without starting a backtest.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>readConfig()});document.modelContext.registerTool({name:'stage_options_configuration',description:'Update known strategy controls for review. Does not run a backtest.',inputSchema:{type:'object',properties:{configuration:{type:'object'}},required:['configuration'],additionalProperties:false},execute:({configuration})=>{if(!configuration||typeof configuration!=='object'||Array.isArray(configuration))throw Error('A configuration object is required');for(const k of Object.keys(configuration))if(!Array.from($('#config-form').elements).some(e=>e.name===k))throw Error('Unknown field '+k);applyConfig(configuration);showView('workspace');return readConfig();}});}catch(e){console.warn('Agent browser tools unavailable',e);}}
