const $ = s => document.querySelector(s);
let catalogData, activeJob, selectedResult = 'overview', selectedRun = 0, pollingId = null;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = (v,d=2) => v == null ? '—' : Number(v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const usd = v => v == null ? '—' : (v < 0 ? '−$' : '$') + num(Math.abs(v));
function notice(message){$('#notice').hidden=!message; $('#notice').textContent=message||'';}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
function showView(id){document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==id);document.querySelectorAll('[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===id));if(id==='history')loadHistory();}
document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>showView(e.dataset.view)));
function readConfig(){const f=new FormData($('#config-form')), config={};for(const [key,val] of f){const element=$(`[name="${key}"]`);config[key]=element.type==='number'?Number(val):val;}if(config.structure==='custom')config.legs=JSON.parse(config.legs);else delete config.legs;return config;}
function applyConfig(config){if(!config||typeof config!=='object'||Array.isArray(config))throw Error('Choose a saved configuration JSON object.');const names=new Set(Array.from($('#config-form').elements).map(e=>e.name));for(const k of Object.keys(config))if(!names.has(k))throw Error('Unknown configuration field: '+k);if(config.legs!==undefined&&(!Array.isArray(config.legs)||config.legs.length>6))throw Error('Custom legs must be an array of up to six rows.');for(const [k,v] of Object.entries(config)){const el=$(`[name="${k}"]`);if(el)el.value=typeof v==='object'?JSON.stringify(v):v;}renderLegs();updateStructure();saveDraft();}
function updateStructure(){const structure=$('#structure').value;$('#custom-legs').hidden=structure!=='custom';$('#put-badge').textContent='−'+num($('[name="put_delta"]').value)+' Δ';$('#call-badge').textContent='+'+num($('[name="call_delta"]').value)+' Δ';$('.leg-diagram').hidden=!['strangle','straddle','condor'].includes(structure);}
$('#config-form').addEventListener('input',()=>{updateStructure();saveDraft();});
async function loadExample(){const config=await api('/api/presets/strangle-20-delta');applyConfig(config);showView('workspace');notice('Guide example loaded. Review the inputs, then click Run backtest.');}
$('#load-example').onclick=()=>loadExample().catch(e=>notice(e.message));
$('#save-config').onclick=()=>{try{const blob=new Blob([JSON.stringify(readConfig(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='options-lab-config.json';a.click();URL.revokeObjectURL(a.href);notice('Configuration downloaded. Import it from Run history to reuse it.');}catch(e){notice(e.message);}};
$('#import-button').onclick=()=>$('#import-file').click();
$('#import-file').onchange=async e=>{try{applyConfig(JSON.parse(await e.target.files[0].text()));showView('workspace');notice('Configuration loaded. Review the controls before running.');}catch(e){notice('Could not import: '+e.message);}};
$('#config-form').onsubmit=async e=>{e.preventDefault();try{notice('');const job=await api('/api/runs',readConfig());localStorage.setItem('optionsLabActive',job.id);await poll(job.id);}catch(e){notice(e.message);}};
$('#cancel').onclick=async()=>{if(activeJob)await api(`/api/runs/${activeJob.id}/cancel`,{});};
async function poll(id){pollingId=id;localStorage.setItem('optionsLabActive',id);try{const job=await api('/api/runs/'+id);if(pollingId!==id)return;activeJob=job;const running=['queued','running'].includes(job.status);$('#run-button').disabled=running;$('#progress-area').hidden=!running;$('#run-status').textContent=job.status.toUpperCase();$('#progress-label').textContent=job.message;$('#progress-bar').style.width=(job.progress*100)+'%';if(running)setTimeout(()=>{if(pollingId===id)poll(id);},1500);else if(job.result){selectedRun=job.result.selected_index;renderResults();}else notice(job.message);}catch(e){notice(e.message);$('#run-button').disabled=false;}}

async function loadHistory(){try{const runs=await api('/api/runs');$('#history-content').innerHTML=runs.length?runs.map(j=>`<div class="run-item"><div><strong>${esc(j.request.name)}</strong><small>${esc(j.request.start)} → ${esc(j.request.end)} · ${esc(j.created.slice(0,16).replace('T',' '))} UTC</small></div><span class="pill">${esc(j.status)}</span><button class="secondary" data-load="${j.id}">Open result</button><button class="text-button" data-reuse="${j.id}">Reuse rules ↗</button></div>`).join(''):'<p class="muted">Your completed and interrupted runs will be saved here.</p>';document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{showView('workspace');poll(b.dataset.load);});document.querySelectorAll('[data-reuse]').forEach(b=>b.onclick=async()=>{const j=await api('/api/runs/'+b.dataset.reuse);applyConfig(j.request);showView('workspace');});}catch(e){notice(e.message);}}
async function init(){try{renderLegs();const draft=localStorage.getItem('optionsLabDraft');if(draft){try{applyConfig(JSON.parse(draft));}catch(e){localStorage.removeItem('optionsLabDraft');notice('An invalid saved browser draft was ignored.');}}const preset=new URLSearchParams(location.search).get('preset');if(preset==='strangle-20-delta'){await loadExample();history.replaceState(null,'','/');}catalogData=await api('/api/catalog');const months=catalogData.months;$('#data-title').textContent=`${months.length} monthly option files · ${months[0]?.month||'No data'} — ${months.at(-1)?.month||''}`;$('#data-detail').textContent=catalogData.kind;$('#data-size').textContent=num(catalogData.bytes/1024**3,1)+' GB ON DISK';$('#catalog-root').textContent=catalogData.root;$('#catalog-content').innerHTML='<div class="table-wrap"><table><thead><tr><th>Month</th><th>Options</th><th>Futures</th><th>Pair status</th></tr></thead><tbody>'+months.map(m=>`<tr><td>${m.month}</td><td>${num(m.option_bytes/1024**2,1)} MB</td><td>${num(m.future_bytes/1024**2,1)} MB</td><td>${m.paired?'Both files present':'Missing futures'}</td></tr>`).join('')+'</tbody></table></div>';const id=localStorage.getItem('optionsLabActive');if(id)poll(id);}catch(e){notice(e.message);}}
function saveDraft(){try{localStorage.setItem('optionsLabDraft',JSON.stringify({...readConfig(),legs:JSON.parse($('[name="legs"]').value)}));}catch(e){/* Invalid unfinished input remains editable. */}}
function renderLegs(){let legs;try{legs=JSON.parse($('[name="legs"]').value);}catch(e){legs=[];}$('#leg-rows').innerHTML=legs.map((l,i)=>`<div class="leg-editor" data-leg-row="${i}"><label>Side<select data-leg-key="side"><option value="sell" ${l.side==='sell'?'selected':''}>Sell</option><option value="buy" ${l.side==='buy'?'selected':''}>Buy</option></select></label><label>Type<select data-leg-key="type"><option value="P" ${l.type==='P'?'selected':''}>Put</option><option value="C" ${l.type==='C'?'selected':''}>Call</option></select></label><label>Absolute delta<input data-leg-key="delta" type="number" min="0.01" max="0.95" step="0.01" value="${esc(l.delta)}"></label><label>Ratio<input data-leg-key="ratio" type="number" min="1" max="10" value="${esc(l.ratio)}"></label><button type="button" class="text-button" data-remove-leg="${i}" aria-label="Remove leg ${i+1}">×</button></div>`).join('');document.querySelectorAll('[data-leg-key]').forEach(el=>el.onchange=()=>{const rows=Array.from(document.querySelectorAll('[data-leg-row]')).map(row=>Object.fromEntries(Array.from(row.querySelectorAll('[data-leg-key]')).map(input=>[input.dataset.legKey,['delta','ratio'].includes(input.dataset.legKey)?Number(input.value):input.value])));$('[name="legs"]').value=JSON.stringify(rows);saveDraft();});document.querySelectorAll('[data-remove-leg]').forEach(el=>el.onclick=()=>{legs=JSON.parse($('[name="legs"]').value);legs.splice(Number(el.dataset.removeLeg),1);$('[name="legs"]').value=JSON.stringify(legs);renderLegs();saveDraft();});$('#add-leg').disabled=legs.length>=6;}
$('#add-leg').onclick=()=>{const legs=JSON.parse($('[name="legs"]').value);if(legs.length<6)legs.push({type:'C',side:'buy',delta:.1,ratio:1});$('[name="legs"]').value=JSON.stringify(legs);renderLegs();saveDraft();};
init();
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function stats(items){return '<div class="stats-list">'+items.map(([label,value])=>`<div class="stat"><small>${esc(label)}</small><strong>${value}</strong></div>`).join('')+'</div>';}
function equityChart(curve){if(!curve?.length)return '<p class="muted">No marked equity observations.</p>';const W=800,H=310,left=70,right=16,top=18,bottom=37;const minT=Date.parse(curve[0].time),maxT=Date.parse(curve.at(-1).time);let lo=Math.min(...curve.map(p=>p.equity)),hi=Math.max(...curve.map(p=>p.equity));const padding=Math.max((hi-lo)*.15,1);lo-=padding;hi+=padding;const x=t=>left+(Date.parse(t)-minT)/(maxT-minT||1)*(W-left-right);const y=v=>top+(hi-v)/(hi-lo)*(H-top-bottom-45);const pts=curve.map(p=>`${x(p.time).toFixed(1)},${y(p.equity).toFixed(1)}`).join(' ');const ddmax=Math.max(...curve.map(p=>-p.drawdown),1);const dd=curve.map(p=>`${x(p.time).toFixed(1)},${(H-bottom-35-p.drawdown/ddmax*30).toFixed(1)}`).join(' ');let grid='';for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3;grid+=`<line x1="${left}" y1="${y(v)}" x2="${W-right}" y2="${y(v)}" stroke="#30383c" stroke-dasharray="3 5"/><text x="${left-10}" y="${y(v)+4}" text-anchor="end" class="chart-label">${num(v,0)}</text>`;}return `<svg class="chart-real" viewBox="0 0 ${W} ${H}" role="img" aria-label="Equity curve in USD and observed drawdown"><defs><linearGradient id="equityFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#c2ff74" stop-opacity=".16"/><stop offset="1" stop-color="#c2ff74" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${left},${H-bottom-45} ${pts} ${W-right},${H-bottom-45}" fill="url(#equityFill)"/><polyline points="${pts}" fill="none" stroke="#c2ff74" stroke-width="1.8"/><polyline points="${dd}" fill="none" stroke="#ed8c92" stroke-width="1.3"/><text x="${left}" y="${H-8}" class="chart-label">${curve[0].time.slice(0,10)}</text><text x="${W-right}" y="${H-8}" text-anchor="end" class="chart-label">${curve.at(-1).time.slice(0,10)}</text></svg>`;}
function renderResults(){const result=activeJob.result,run=result.runs[selectedRun],m=run.metrics;$('#result-title').textContent=run.config.name;$('#run-status').textContent=m.unresolved_count?'UNRESOLVED EXPOSURE':'COMPLETED';$('#progress-area').hidden=true;$('#metrics').innerHTML=[['Net P&L',usd(m.net_pnl),'After fees & slippage',m.net_pnl>=0?'positive':'negative'],['Max drawdown',usd(m.max_drawdown),'Observed · '+num(m.max_drawdown_pct)+'%','negative'],['Sharpe ratio',num(m.sharpe),'Daily returns · √365',''],['Win rate',m.win_rate==null?'—':num(m.win_rate,1)+'%',m.trade_count+' closed positions','']].map(([l,v,s,c])=>`<article><small>${l}</small><strong class="${c}">${v}</strong><span>${s}</span></article>`).join('');$('#equity-chart').className='';$('#equity-chart').innerHTML=equityChart(m.curve);$('#exports').hidden=false;$('#export-json').href=`/api/runs/${activeJob.id}/export`;$('#export-csv').href=`/api/runs/${activeJob.id}/trades.csv?variant=${selectedRun}`;const warnings=[];if(m.unresolved_count)warnings.push('An exit could not be completed. Further entries stopped; headline performance is unavailable. Inspect Audit and the trade ledger.');if(run.missing_days.length)warnings.push(`${run.missing_days.length} dates have missing source data. This is a partial sample.`);if(m.trade_count<20)warnings.push('Small sample: fewer than 20 closed positions. Ratios are descriptive, not evidence of a stable edge.');if(result.runs.length>1&&!result.winner_selected)warnings.push('No configuration met the development ranking requirements. The first variant is shown; no winner was selected.');if(m.mark_coverage_pct!=null&&m.mark_coverage_pct<95)warnings.push(`${num(m.mark_coverage_pct,1)}% of risk events had fresh marks. Drawdown may be understated.`);notice(warnings.join(' '));renderResultTab();}
document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{selectedResult=b.dataset.result;document.querySelectorAll('[data-result]').forEach(e=>e.classList.toggle('active',e===b));if(activeJob?.result)renderResultTab();});
function renderResultTab(){const result=activeJob.result,run=result.runs[selectedRun],m=run.metrics,c=run.config,out=$('#result-content');
if(selectedResult==='overview'){const monthly={};for(const d of m.daily)monthly[d.date.slice(0,7)]=(monthly[d.date.slice(0,7)]||0)+d.pnl;out.innerHTML=stats([['Return on starting capital',num(m.return_pct)+'%'],['Profit factor',num(m.profit_factor)],['Sortino',num(m.sortino)],['Average trade',usd(m.average_trade)],['Total fees',usd(m.fees)],['Slippage cost',usd(m.slippage)],['Best trade',usd(m.best_trade)],['Worst trade',usd(m.worst_trade)],['Calendar sample',m.sample_days+' days']])+`<div class="info-banner">${esc(c.structure.replaceAll('_',' '))} · ${num(c.quantity_btc,3)} BTC per base leg · ${c.entry_time}–${c.exit_time} UTC · ${c.start} → ${c.end}<br>Observed drawdown uses available tick marks; execution windows and stale intervals can hide additional losses.</div><h3 style="font-size:14px">Monthly realized P&L</h3><div class="heatmap">${Object.entries(monthly).map(([month,p])=>`<div class="heat-cell ${p<0?'loss':''}"><small>${month}</small><b class="${p<0?'negative':'positive'}">${usd(p)}</b></div>`).join('')}</div>`;}
if(selectedResult==='trades'){out.innerHTML='<div class="subhead"><h3>Position ledger</h3><small>Click a date for legs, Greeks & individual fills</small></div>'+table(['Date / details','Entry UTC','Exit','Credit','Fees','Net P&L','Status'],run.trades.map((t,i)=>[`<button data-trade="${i}">${esc(t.date)} ↗</button>`,esc(t.entry_time.slice(11,19)),esc(t.exit_reason.replaceAll('_',' ')),usd(t.entry_credit),usd(t.fees),`<span class="${t.net_pnl<0?'negative':'positive'}">${usd(t.net_pnl)}</span>`,esc(t.status)]))+'<div id="trade-detail"></div>';document.querySelectorAll('[data-trade]').forEach(b=>b.onclick=()=>{const t=run.trades[Number(b.dataset.trade)];$('#trade-detail').innerHTML='<div class="info-banner">Decision '+esc(t.decision_time)+'<br>Entry complete '+esc(t.entry_time)+'<br>Exit trigger '+esc(t.exit_trigger)+'<br>'+esc(t.execution_window_risk)+'</div>'+table(['Leg','Side','BTC filled','IV','Delta','Gamma','Theta/day','Vega/1pt'],t.legs.map(l=>[esc(l.symbol),esc(l.side),num(l.quantity_btc,3),num(l.greeks.iv*100,1)+'%',num(l.greeks.delta,3),num(l.greeks.gamma,6),num(l.greeks.theta),num(l.greeks.vega)]))+`<details><summary>Individual fill evidence & risk path</summary><pre class="ledger-detail">${esc(JSON.stringify(t,null,2))}</pre></details>`;});}
if(selectedResult==='risk'){const entries=run.trades;out.innerHTML=stats([['Observed worst excursion',usd(entries.length?Math.min(...entries.map(t=>t.mae)):null)],['Trade expected shortfall (95%)',usd(m.expected_shortfall_95)],['Fresh mark coverage',num(m.mark_coverage_pct,1)+'%'],['Peak reserve',usd(entries.length?Math.max(...entries.map(t=>t.margin_reserve)):null)],['Incomplete entries',run.quality.incomplete_entries],['Unresolved positions',m.unresolved_count]])+'<div class="info-banner">Greeks below are model estimates at the entry decision, signed and scaled by filled BTC. Vega is USD per 1 volatility point; theta is USD per day. Minute-sampled portfolio Greeks during the position are included in the full result.</div>'+table(['Date','Portfolio Δ (BTC)','Gamma','Theta / day','Vega / 1pt','MAE','MFE'],entries.map(t=>[esc(t.date),num(t.entry_greeks.delta,4),num(t.entry_greeks.gamma,6),usd(t.entry_greeks.theta),usd(t.entry_greeks.vega),usd(t.mae),usd(t.mfe)]));}
if(selectedResult==='compare'){if(result.runs.length===1){out.innerHTML='<div class="empty-card"><h3>Test the neighborhood of your idea.</h3><p>Open Parameter experiment in the builder and choose a grid of deltas, stops, and profit targets. Use at least 10 days; larger samples are more informative.</p></div>';return;}out.innerHTML=`<div class="subhead"><h3>Development → holdout</h3><span class="tag">SPLIT ${result.split_date}</span></div><p class="muted" style="font-size:12px;margin-bottom:16px">Ranking uses development ${esc(c.objective)} only. Holdout starts ${result.split_date}. ${result.winner_selected?'Selected configuration is marked below.':'No eligible winner.'} Repeatedly tuning to the holdout invalidates it.</p>`+table(['Variant','|Δ|','SL %','TP %','Dev trades','Dev P&L','Dev Sharpe','Dev DD','Holdout P&L','Holdout Sharpe','Status'],result.runs.map((r,i)=>[`<button data-variant="${i}">${result.winner_selected&&i===result.selected_index?'★ ':''}#${i+1} ↗</button>`,num(r.config.call_delta),num(r.config.stop_loss_pct,0),num(r.config.take_profit_pct,0),r.development.trade_count,usd(r.development.net_pnl),num(r.development.sharpe),usd(r.development.max_drawdown),usd(r.holdout.net_pnl),num(r.holdout.sharpe),r.eligible?'Eligible':'Insufficient / invalid']));document.querySelectorAll('[data-variant]').forEach(b=>b.onclick=()=>{selectedRun=Number(b.dataset.variant);renderResults();});}
if(selectedResult==='audit'){out.innerHTML=`<div class="subhead"><h3>Evidence & limitations</h3><span class="tag">${esc(result.engine_version)}</span></div><div class="info-banner">${result.assumptions.map(esc).join('<br>')}</div>`+stats([['Missing source dates',run.missing_days.length],['Invalid Greek observations',run.quality.invalid_greek_events],['Closed realized P&L',usd(m.realized_closed_pnl)]])+'<h3 style="font-size:14px;margin:24px 0 10px">Entry attempts & skipped dates</h3>'+table(['Reason','Count'],Object.entries(run.skips).map(([k,v])=>[esc(k.replaceAll('_',' ')),v]))+'<small>Selection reasons count minute-by-minute attempts; no-entry and missing-data counters count days.</small>'+`<details><summary>Source fingerprints & ingestion quality</summary><pre class="ledger-detail">${esc(JSON.stringify(result.sources.map(s=>({path:s.path,bytes:s.bytes,sha256:s.sha256,quality:s.quality,days:s.days.length})),null,2))}</pre></details><details><summary>Exact configuration</summary><pre class="ledger-detail">${esc(JSON.stringify(c,null,2))}</pre></details>`;}}
// The visible configuration is also exposed to supporting agent-enabled browsers.
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_options_configuration',description:'Read the visible Bitcoin options strategy controls without starting a backtest.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>readConfig()});document.modelContext.registerTool({name:'stage_options_configuration',description:'Update known strategy controls for review. Does not run a backtest.',inputSchema:{type:'object',properties:{configuration:{type:'object'}},required:['configuration'],additionalProperties:false},execute:({configuration})=>{if(!configuration||typeof configuration!=='object'||Array.isArray(configuration))throw Error('A configuration object is required');for(const k of Object.keys(configuration))if(!Array.from($('#config-form').elements).some(e=>e.name===k))throw Error('Unknown field '+k);applyConfig(configuration);showView('workspace');return readConfig();}});}catch(e){console.warn('Agent browser tools unavailable',e);}}
